mode: balance #模式 balance(均衡模式)、parallel(平行模式)
containers: #容器，可配置多个
  - address: http://192.168.31.233:5700 #青龙、v1v2v3v4v5访问地址
    username: admin #用户名-青龙（config文件夹-auth.json文件找）
    password: admin #密码（青龙config文件夹-auth.json文件找）
    cid: #openapi 用户名
    secret: #openapi 密码
    weigth:  #权重 balance模式下权重越高分得的ck越多，默认1
    mode: parallel #单独对容器进行模式设置（自己选）
    limit:  #限制容器ck数目
 #- address: http://192.168.31.233:5525 ##（单容器注释，多容器保留）
  #  username: admin
  #  password: admin
  # - path: /ql/config/config.sh #本地配置文件路径 v1v2v3v4v5和不知名容器的配置
  #- path: /Users/cdle/Desktop/jd_study/jdc/list.sh
AtTime: 6 #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp: true #填写true或者false  false
IsOldV4: false #填写true或者false  false是否新版或者旧版V4
ApiToken: #为空默认随机禁用
Wskey: true # 填空默认禁用wskey转换 需要的填true

theme:  #https://ghproxy.com/https://raw.githubusercontent.com/58563528/DDD/main/theme/noodin.html #自定义主题，支持本地、网络路径（我喜欢吃面）
static: ./static #静态文件 便于自定义二维码页面时，引入css、js等文件（不用动）
master: jd_xxxxx #管理员账户pin，有多个用'&'拼接
#数据库 支持sqlite3、mysql和postgres
#sqlite3 填路径，默认 ./.dmm
#mysql填 user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
#postgres填 host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
database: /ql/db/.xdd.db  #数据库位置，默认./.xdd.db #（强迫症的我还是给它找了个家，路径按自己的来改）
qywx_key:  #企业微信推送key（这个就是企业微信机器人的key）
daily_push:  #定时任务（这个我暂时没有配置）
resident: #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。（这个我也没配置，多容器自己试试）
#自定义ua
user_agent:
telegram_bot_token:  #telegram bot token（这个应该不用再说了吧）
telegram_user_id:  #telegrame user id（这个应该不用再说了吧）
qquid:  #接收通知的qq号（这个填你的群主qq号码，和扫码配置的qq机器人分开，需要2个qq号）
qqgid:  #监听的群
qbot_public_mode: true
default_priority: #新用户默认优先级（默认就行，默认是1）
no_ghproxy: true #更新资源是否不使用代理 默认false
qbot_public_mode: true  #qq机器人群聊模式，默认私聊模式（默认false）
daily_asset_push_cron: 0 9 * * * #日常资产推送时间

repos:
  - git: https://github.com/shufflewzc/faker2.git